#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
# Accepts 4 parameters:
#	1. The path to the file to be transferred
#	2. The IP of the server we want to transfer the file to
#	3. The username scp connects with
#	4. The path to the SSH private key that scp uses
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# if less than 3 parameters passed
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp

# Check if less than 3 parameters were passed
if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Transfer file using scp
if [ -z "$path_to_ssh_key" ]; then
  scp -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip:~/"
else
  scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
fi

