#!/usr/bin/env bash
# Installs nginx server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
# using curl, it must return a page that contains
# the string Hello World!
# You can’t use systemctl for restarting nginx

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
