#!/usr/bin/env bash
# fixing why nginx is not listening on port 80

rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
