#!/usr/bin/env bash
# Fixes web server to run nginx as the nginx user listening on port 8080

sudo service nginx stop
sudo pkill apache2

#set a user in the config by replacing '#user' and it's value
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

#replace port 80 with 8080 in the sites-available config
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default

sudo nginx -t

#start nginx with the new nginx user
sudo service nginx start
